- name: Update conda envs
  uses: snakemake/snakedeploy-github-action@v1
  with:
    subcommand: update-conda-envs
    args: workflow/envs/*.yaml

- name: Update conda envs and also create pinnings
  uses: snakemake/snakedeploy-github-action@v1
  with:
    subcommand: update-conda-envs
    args: workflow/envs/*.yaml --pin-envs

- name: Update pinnings
  uses: snakemake/snakedeploy-github-action@v1
  with:
    subcommand: pin-conda-envs
    args: workflow/envs/*.yaml
